### ISSUE TITLE
could not load script

### ISSUE THREAD

**Issue by toxydose** [scipag/httprecon-nse#2]
I have an error launching or adding to nmap db this script
> sudo nmap --script-updatedb 

Starting Nmap 7.40 ( https://nmap.org ) at 2017-09-28 23:38 EEST
NSE: Updating rule database.
NSE: Failed to load /usr/bin/../share/nmap/scripts//httprecon.nse:
/usr/bin/../share/nmap/scripts//httprecon.nse:69: variable 'shortport' is not declared
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nselib/strict.lua:80: in metamethod '__index'
	/usr/bin/../share/nmap/scripts//httprecon.nse:69: in function </usr/bin/../share/nmap/scripts//httprecon.nse:1>
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:615: could not load script
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nse_main.lua:615: in field 'new'
	/usr/bin/../share/nmap/nse_main.lua:1255: in main chunk
	[C]: in ?

QUITTING!

**Comment by marcruef** [comment]
Thanks for the bug report. I have just fixed that. You may now copy the main file _httprecon.nse_ into the root folder of your scripts (e.g. `/usr/share/nmap/scripts`). The db files need to be present in their according sub-folders in the scripts folder (e.g. `/usr/share/nmap/scripts/get_existing`). Otherwise you may initiate such a scan with `--script=httprecon`.
